version: '3.7'
services:

  iris:
    build:
      context: .
    image: tc_innovation_toolkit
    hostname: iris
    command: -b "sudo service apache2 start" --check-caps false
    ports:
    - "52773:52773"
    - "12773:51773"
    - "443:443"
    - "1972:1972"
